- name : Demo on play level variable
  hosts : all
  vars :
    URL : play.example.com
    tasks:
      - name : print URL
        ansible.builtin.debug:
          msg : url - {{ URL }}

- name : Demo on Task level variable
  hosts : all
  tasks :
    - name : print URL
      ansible.built.in.debug:
        msg: url - {{ URL }}
        vars:
          URL: play.example.com




