- name : Demo on play level variable
  hosts : all
  vars :
    URL : ram.example.com
  tasks:
      - name : print URL
        ansible.builtin.debug:
          msg : url - {{ URL }}

- name : Demo on play level variable
  hosts : all
  vars_files:
    - ex-vars.yml
  tasks:
    - name : print URL
      ansible.builtin.debug:
        msg : url - {{ URL }}

- name : Demo on Task level variable
  hosts : all
  tasks :
    - name : print URL
      ansible.builtin.debug:
        msg: url - {{ URL }}
      vars:
        URL: play.example.com

##- name : variable from roles
  ##hosts : all
  ##roles :
    ##- sample

- name: Demo on register variables
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: print output
      ansible.builtin.debug:
          msg: "{{ output }}"








